Skip to content
Search or jump to…

Pull requests
Issues
Marketplace
Explore
 
@LilaKelland 
noahgift
/
Python-Functions-from-Zero
1
31
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Python-Functions-from-Zero/.github/workflows/main.yml
@noahgift
noahgift Create main.yml
Latest commit b466456 on Feb 11
 History
 1 contributor
29 lines (23 sloc)  510 Bytes
  
name: Python application test with Github Actions

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        make install
    - name: Lint with pylint
      run: |
        make lint
    - name: Test with pytest
      run: |
        make test
    - name: Format code
      run: |
        make format
    
    
